New relic
EarthlingInteractive/fssk-node pull request #27
Opened 2019-03-27 21:21 UTC by jpchip

Add new relic to project. See corresponding PR for react: https://github.com/EarthlingInteractive/fssk-react-client/pull/7

2019-03-27 21:24 UTC, jpchip commented
it definitely logged something: https://earthlinginteractive.slack.com/files/UD5KPGZ6Y/FHCUD7YVB/capture.png

2019-04-01 22:11 UTC, sbrudz requested changes
This looks good except for the unhandled error case noted in the comment

2019-04-02 16:01 UTC, jpchip commented on server/src/app.ts
> +			const result = data.replace(/<meta name="__NEW_RELIC_SCRIPT__">/g, newrelic.getBrowserTimingHeader());
added check for this.

2019-04-23 22:47 UTC, sbrudz approved these changes

2019-04-23 22:47 UTC, merged